# Generated by Django 2.2.13 on 2021-02-07 01:20

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190718_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_of_nationality',
            field=django_countries.fields.CountryField(blank=True, default='US', max_length=2, verbose_name='Country of Nationality'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_of_residence',
            field=django_countries.fields.CountryField(default='US', max_length=2, verbose_name='Country'),
        ),
    ]
