# Generated by Django 2.2.24 on 2021-07-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20210709_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='app_label',
            field=models.CharField(blank=True, choices=[('compressor', 'compressor'), ('joyous', 'joyous'), ('mptt', 'mptt'), ('publications', 'publications'), ('projects', 'projects'), ('standard', 'standard'), ('hmap', 'hmap'), ('drp', 'drp'), ('mlp', 'mlp'), ('hrp', 'hrp'), ('lgrp', 'lgrp'), ('eppe', 'eppe'), ('gdb', 'gdb'), ('omo_mursi', 'omo_mursi'), ('origins', 'origins'), ('psr', 'psr'), ('cc', 'cc'), ('fc', 'fc'), ('wtap', 'wtap'), ('arvrc', 'arvrc'), ('eval', 'eval'), ('paleosites', 'paleosites')], max_length=100, null=True),
        ),
    ]
