# Generated by Django 3.2.12 on 2022-05-18 20:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_projectpage_app_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='extent',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='app_label',
            field=models.CharField(blank=True, choices=[('compressor', 'compressor'), ('joyous', 'joyous'), ('mptt', 'mptt'), ('cookielaw', 'cookielaw'), ('rest_framework', 'rest_framework'), ('publications', 'publications'), ('projects', 'projects'), ('standard', 'standard'), ('drp', 'drp'), ('mlp', 'mlp'), ('hrp', 'hrp'), ('lgrp', 'lgrp'), ('eppe', 'eppe'), ('gdb', 'gdb'), ('omo_mursi', 'omo_mursi'), ('origins', 'origins'), ('psr', 'psr'), ('cc', 'cc'), ('fc', 'fc'), ('wtap', 'wtap'), ('arvrc', 'arvrc'), ('eval', 'eval'), ('paleosites', 'paleosites'), ('turkana', 'turkana'), ('sermar', 'sermar'), ('utcasts', 'utcasts'), ('wormil', 'wormil')], max_length=100, null=True),
        ),
    ]
