# Generated by Django 2.2.13 on 2020-10-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_initial_data'),
        ('origins', '0002_site_location_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='references',
            field=models.ManyToManyField(blank=True, to='publications.Publication'),
        ),
    ]
