# Generated by Django 2.2.13 on 2020-10-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_initial_data'),
        ('origins', '0004_taxon_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='fossil',
            name='references',
            field=models.ManyToManyField(blank=True, to='publications.Publication'),
        ),
    ]
