# Generated by Django 2.2.13 on 2020-10-31 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0005_fossil_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='max_epoch',
            field=models.CharField(blank=True, choices=[('Holocene', 'Holocene'), ('Pleistocene', 'Pleistocene'), ('Pliocene', 'Pliocene'), ('Miocene', 'Miocene'), ('Oligocene', 'Oligocene'), ('Eocene', 'Eocene'), ('Paleocene', 'Paleocene')], help_text='Maximum Chronostratigraphic Series/Epoch', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='max_period',
            field=models.CharField(blank=True, choices=[('Quaternary', 'Quaternary'), ('Neogene', 'Neogene'), ('Paleogene', 'Paleogene'), ('Cretaceous', 'Cretaceous')], help_text='Maximum Chronostratigraphic System/Period', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='max_stage',
            field=models.CharField(blank=True, choices=[('Upper', 'Upper'), ('Middle', 'Middle'), ('Calabrian', 'Calabrian'), ('Gelasian', 'Gelasian'), ('Piacenzian', 'Piacenzian'), ('Zanclean', 'Zanclean'), ('Messinian', 'Messinian'), ('Tortonian', 'Tortonian'), ('Seravallian', 'Seravallian'), ('Langhian', 'Langhian'), ('Burdigalian', 'Burdigalian'), ('Aquitanian', 'Aquitanian')], help_text='Maximum Chronostratigraphic Age/Stage', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='min_epoch',
            field=models.CharField(blank=True, choices=[('Holocene', 'Holocene'), ('Pleistocene', 'Pleistocene'), ('Pliocene', 'Pliocene'), ('Miocene', 'Miocene'), ('Oligocene', 'Oligocene'), ('Eocene', 'Eocene'), ('Paleocene', 'Paleocene')], help_text='Minimum Chronostratigraphic Series/Epoch', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='min_period',
            field=models.CharField(blank=True, choices=[('Quaternary', 'Quaternary'), ('Neogene', 'Neogene'), ('Paleogene', 'Paleogene'), ('Cretaceous', 'Cretaceous')], help_text='Minimum Chronostratigraphic System/Period', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='min_stage',
            field=models.CharField(blank=True, choices=[('Upper', 'Upper'), ('Middle', 'Middle'), ('Calabrian', 'Calabrian'), ('Gelasian', 'Gelasian'), ('Piacenzian', 'Piacenzian'), ('Zanclean', 'Zanclean'), ('Messinian', 'Messinian'), ('Tortonian', 'Tortonian'), ('Seravallian', 'Seravallian'), ('Langhian', 'Langhian'), ('Burdigalian', 'Burdigalian'), ('Aquitanian', 'Aquitanian')], help_text='Minimum Chronostratigraphic Age/Stage', max_length=50, null=True),
        ),
    ]
