# Generated by Django 2.2.13 on 2020-10-31 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0007_auto_20201031_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='fossil',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='origins.Taxon'),
        ),
    ]
