# Generated by Django 2.2.13 on 2020-10-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0008_fossil_taxon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Site Naem'),
        ),
    ]
