# Generated by Django 2.2.13 on 2020-10-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_initial_data'),
        ('origins', '0010_auto_20201031_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='references',
            field=models.ManyToManyField(blank=True, to='publications.Publication'),
        ),
    ]
