# Generated by Django 2.2.13 on 2020-10-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0011_context_references'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxon',
            options={'ordering': ['rank__ordinal', 'label'], 'verbose_name': 'Taxon', 'verbose_name_plural': 'Taxa'},
        ),
        migrations.AddField(
            model_name='fossil',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
