# Generated by Django 2.2.13 on 2020-10-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0012_auto_20201031_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='fossil',
            name='year_collected',
            field=models.IntegerField(blank=True, help_text='The year, event or field campaign during which the item was found.', null=True, verbose_name='Year'),
        ),
    ]
