# Generated by Django 2.2.13 on 2021-03-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0014_mptttaxon'),
    ]

    operations = [
        migrations.AddField(
            model_name='fossil',
            name='other_catalog_numbers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
