# Generated by Django 2.2.19 on 2021-03-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20210306_0019'),
        ('origins', '0015_fossil_other_catalog_numbers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mptttaxon',
            options={'ordering': ['rank__ordinal', 'label'], 'verbose_name': 'Taxon', 'verbose_name_plural': 'Taxa'},
        ),
        migrations.AddField(
            model_name='mptttaxon',
            name='references',
            field=models.ManyToManyField(blank=True, to='publications.Publication'),
        ),
    ]
