# Generated by Django 2.2.19 on 2021-03-26 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0016_auto_20210326_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='fossil',
            name='mptt_taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='origins.MPTTTaxon'),
        ),
    ]
