# Generated by Django 2.2.19 on 2021-03-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0017_fossil_mptt_taxon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mptttaxon',
            options={'ordering': ['rank__ordinal', 'label'], 'verbose_name': 'MPTaxon', 'verbose_name_plural': 'MPTaxa'},
        ),
        migrations.AlterModelOptions(
            name='taxonrank',
            options={'ordering': ['ordinal'], 'verbose_name': 'Taxon Rank'},
        ),
    ]
