# Generated by Django 2.2.19 on 2021-03-27 16:46

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0018_auto_20210326_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mptttaxon',
            options={'ordering': ['rank__ordinal', 'label'], 'verbose_name': 'TTaxon', 'verbose_name_plural': 'TTaxa'},
        ),
        migrations.AddField(
            model_name='mptttaxon',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mptttaxon',
            name='authorship',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mptttaxon',
            name='epithet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mptttaxon',
            name='junior_to',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='origins.MPTTTaxon'),
        ),
        migrations.AddField(
            model_name='mptttaxon',
            name='nomenclatural_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mptttaxon',
            name='nomenclatural_status',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('junior_synonym', 'junior_synonym')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mptttaxon',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
