# Generated by Django 2.2.19 on 2021-03-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20210326_2356'),
        ('origins', '0019_auto_20210327_1646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MPTTTaxon',
            new_name='TTaxon',
        ),
    ]
