# Generated by Django 2.2.19 on 2021-03-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0020_auto_20210327_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttaxon',
            name='nomenclatural_code',
            field=models.CharField(blank=True, choices=[('ICZN', 'ICZN'), ('ICBN', 'ICBN')], default='ICZN', max_length=255, null=True),
        ),
    ]
