# Generated by Django 2.2.19 on 2021-03-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0021_auto_20210327_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fossil',
            old_name='mptt_taxon',
            new_name='ttaxon',
        ),
    ]
