# Generated by Django 2.2.19 on 2021-03-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0023_auto_20210327_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttaxon',
            name='nomenclatural_status',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('junior_synonym', 'junior_synonym')], max_length=255, null=True, verbose_name='Nom. Status'),
        ),
    ]
