# Generated by Django 2.2.19 on 2021-03-31 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0024_auto_20210330_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttaxon',
            name='zoobank_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
