# Generated by Django 2.2.19 on 2021-04-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0025_ttaxon_zoobank_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttaxon',
            name='nomenclatural_status',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('junior_synonym', 'junior_synonym'), ('supressed', 'supressed')], max_length=255, null=True, verbose_name='Nom. Status'),
        ),
    ]
