# Generated by Django 2.2.19 on 2021-04-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0026_auto_20210401_0452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ttaxon',
            options={'ordering': ['rank__ordinal', 'name'], 'verbose_name': 'TTaxon', 'verbose_name_plural': 'TTaxa'},
        ),
        migrations.AddField(
            model_name='ttaxon',
            name='type_specimen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
