# Generated by Django 2.2.19 on 2021-05-03 21:20

from django.db import migrations, models
import publications.models.publication


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0027_auto_20210417_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttaxon',
            name='name_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=publications.models.publication.Publication, to='origins.Reference'),
        ),
    ]
