# Generated by Django 2.2.19 on 2021-05-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0030_ttaxon_name_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttaxon',
            name='paratypes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
