# Generated by Django 2.2.19 on 2021-05-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0031_ttaxon_paratypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttaxon',
            name='type_status',
            field=models.CharField(blank=True, choices=[('holotype', 'Holotype'), ('paratype', 'Paratype'), ('lectotype', 'Lectotype'), ('neotype', 'Neotype'), ('syntype', 'Syntype')], max_length=255, null=True),
        ),
    ]
