# Generated by Django 2.2.19 on 2021-05-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0033_auto_20210504_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttaxon',
            name='classification_status',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('junior_synonym', 'junior_synonym'), ('supressed', 'supressed')], default='ICZN', max_length=255, null=True),
        ),
    ]
