# Generated by Django 2.2.19 on 2021-05-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0034_ttaxon_classification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttaxon',
            name='classification_status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('junior_synonym', 'Junior Synonym'), ('supressed', 'Supressed')], default='ICZN', max_length=255, null=True),
        ),
    ]
