# Generated by Django 2.2.19 on 2021-05-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0037_ttaxon_verbatim_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fossil',
            name='collected_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fossil',
            name='date_discovered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fossil',
            name='discovered_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fossil',
            name='naan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
