# Generated by Django 2.2.19 on 2021-06-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0039_nomen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomen',
            name='year',
            field=models.IntegerField(blank=True, help_text='The year the name was published in yyyy format.', null=True),
        ),
    ]
