# Generated by Django 2.2.21 on 2021-06-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0040_auto_20210604_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomen',
            options={'ordering': ['name'], 'verbose_name': 'Nomen', 'verbose_name_plural': 'Nomina'},
        ),
    ]
