# Generated by Django 2.2.24 on 2021-06-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0042_auto_20210623_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomen',
            name='type_status',
        ),
        migrations.AddField(
            model_name='fossil',
            name='is_type_specimen',
            field=models.BooleanField(default=False, verbose_name='Type Specimen'),
        ),
        migrations.AddField(
            model_name='fossil',
            name='type_status',
            field=models.CharField(blank=True, choices=[('holotype', 'Holotype'), ('paratype', 'Paratype'), ('lectotype', 'Lectotype'), ('neotype', 'Neotype'), ('syntype', 'Syntype')], max_length=255, null=True),
        ),
    ]
