# Generated by Django 2.2.24 on 2021-06-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0043_auto_20210623_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fossil',
            name='holotype',
        ),
        migrations.AlterField(
            model_name='nomen',
            name='is_objective_synonym',
            field=models.BooleanField(default=False, verbose_name='Objective Synonym'),
        ),
    ]
