# Generated by Django 2.2.24 on 2021-07-14 04:32

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('pages', '0026_auto_20210710_0444'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('origins', '0046_auto_20210710_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominaListView',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
                ('body', wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('html', wagtail.core.blocks.RawHTMLBlock())])),
                ('template_string', models.CharField(choices=[('origins/nomina_list_view.html', 'Default Template')], default='pages/standard_page.html', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NominaListViewRelatedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('title', models.CharField(help_text='Link title', max_length=255)),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='origins.NominaListView')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='originssiteindexpagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='originssiteindexpagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='originssiteindexpagerelatedlink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='originssitepage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='originssitepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='originssitepage',
            name='site',
        ),
        migrations.RemoveField(
            model_name='originssitepage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='originssitepagecarouselitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='originssitepagecarouselitem',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='originssitepagecarouselitem',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='originssitepagecarouselitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='originssitepagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='originssitepagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='originssitepagerelatedlink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='originssitepagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='originssitepagetag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='OriginsSiteIndexPage',
        ),
        migrations.DeleteModel(
            name='OriginsSiteIndexPageRelatedLink',
        ),
        migrations.DeleteModel(
            name='OriginsSitePage',
        ),
        migrations.DeleteModel(
            name='OriginsSitePageCarouselItem',
        ),
        migrations.DeleteModel(
            name='OriginsSitePageRelatedLink',
        ),
        migrations.DeleteModel(
            name='OriginsSitePageTag',
        ),
    ]
