# Generated by Django 3.2.5 on 2021-07-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0049_auto_20210714_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomen',
            name='is_subjective_synonym',
            field=models.BooleanField(default=False, verbose_name='Subjective Synonym'),
        ),
    ]
