# Generated by Django 3.2.5 on 2021-07-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0050_nomen_is_subjective_synonym'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurkanaFossil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbatim_catalog_number', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_suffix', models.CharField(blank=True, max_length=256, null=True)),
                ('catalog_number', models.CharField(blank=True, max_length=256, null=True)),
                ('collection_code', models.CharField(blank=True, max_length=256, null=True)),
                ('specimen_number', models.IntegerField(blank=True, null=True)),
                ('specimen_suffix', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
