# Generated by Django 3.2.5 on 2021-07-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0051_turkanafossil'),
    ]

    operations = [
        migrations.AddField(
            model_name='turkanafossil',
            name='region',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
