# Generated by Django 3.2.5 on 2021-07-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0053_auto_20210721_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveNomen',
            fields=[
            ],
            options={
                'verbose_name': 'Nomen',
                'verbose_name_plural': 'Nomina',
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('origins.nomen',),
        ),
    ]
