# Generated by Django 3.2.5 on 2021-07-29 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0054_activenomen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activenomen',
            options={'ordering': ['name'], 'verbose_name': 'Actice Nomen', 'verbose_name_plural': 'Active Nomina'},
        ),
    ]
