# Generated by Django 3.2.5 on 2021-09-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0056_alter_activenomen_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomen',
            name='verified_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nomen',
            name='verified_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
