# Generated by Django 3.2.5 on 2021-09-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0057_auto_20210917_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomen',
            name='verified_by',
            field=models.CharField(blank=True, choices=[('Denne Reed', 'DR'), ('Emily Raney', 'ER'), ('Jyhreh Johnson', 'JJ'), ('Harper Jackson', 'HJ'), ('Nida Virabalin', 'NV')], max_length=255, null=True),
        ),
    ]
