# Generated by Django 3.2.5 on 2021-10-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0060_auto_20211001_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomen',
            old_name='type_specimen',
            new_name='type_specimen_label',
        ),
    ]
