# Generated by Django 3.2.5 on 2021-10-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0063_nomen_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomen',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Available'),
        ),
    ]
