# Generated by Django 3.2.5 on 2021-10-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0065_auto_20211002_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomen',
            name='zoobank_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
