# Generated by Django 3.2.5 on 2021-10-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0066_nomen_zoobank_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fossil',
            name='vif',
            field=models.BooleanField(default=False),
        ),
    ]
