# Generated by Django 3.2.5 on 2021-11-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0068_auto_20211010_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomen',
            name='is_potentially_valid',
            field=models.BooleanField(default=False, verbose_name='Pot. Valid'),
        ),
    ]
