# Generated by Django 3.2.5 on 2021-11-27 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0069_nomen_is_potentially_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomen',
            old_name='nomenclatural_status',
            new_name='bc_status',
        ),
        migrations.RenameField(
            model_name='ttaxon',
            old_name='nomenclatural_status',
            new_name='bc_status',
        ),
    ]
