# Generated by Django 3.2.5 on 2021-11-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0070_auto_20211127_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomen',
            name='nomenclatural_status',
            field=models.CharField(blank=True, choices=[('unavailable', 'unavailable'), ('invalid', 'invalid'), ('potentially_valid', 'potentially valid')], max_length=255, null=True, verbose_name='Nom. Status'),
        ),
        migrations.AlterField(
            model_name='nomen',
            name='bc_status',
            field=models.CharField(blank=True, choices=[('valid', 'Valid'), ('invalid_gh', 'Invalid GH'), ('invalid_ga', 'Invalid GA'), ('invalid_gb', 'Invalid GB'), ('invalid_sh', 'Inavlid SH'), ('invalid_sm', 'Invalid SM'), ('invalid_sn', 'Invalid SN'), ('invalid_so', 'Inavlid SO'), ('suppressed', 'Supressed')], max_length=255, null=True, verbose_name='BC Status'),
        ),
    ]
