# Generated by Django 3.2.5 on 2021-12-07 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0072_auto_20211127_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurkFossil',
            fields=[
                ('fossil_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='origins.fossil')),
                ('verbatim_inventory_number', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_suffix', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_year_discovered', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_year_mentioned', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_year_published', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_country', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_zone', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_area', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_locality', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_formation', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_member', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_level', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_age_g1', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_age_g2', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_anatomical_part', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_anatomical_description', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_taxonomy1', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_taxonomy2', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_robusticity', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_finder', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_reference_first_mention', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_reference_description', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_reference_identification', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_reference_dating', models.CharField(blank=True, max_length=256, null=True)),
                ('verbatim_region', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('origins.fossil',),
        ),
    ]
