# Generated by Django 3.2.5 on 2021-12-08 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0073_turkfossil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turkfossil',
            old_name='verbatim_region',
            new_name='region',
        ),
    ]
