# Generated by Django 3.2.5 on 2021-12-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0074_rename_verbatim_region_turkfossil_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='turkfossil',
            name='suffix_assigned',
            field=models.BooleanField(null=True),
        ),
    ]
