# Generated by Django 3.2.5 on 2021-12-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0075_turkfossil_suffix_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='turkfossil',
            name='in_origins',
            field=models.BooleanField(null=True),
        ),
    ]
