# Generated by Django 3.2.5 on 2021-12-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0076_turkfossil_in_origins'),
    ]

    operations = [
        migrations.AddField(
            model_name='turkfossil',
            name='to_split',
            field=models.BooleanField(null=True),
        ),
    ]
