# Generated by Django 3.2.5 on 2021-12-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0077_turkfossil_to_split'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turkfossil',
            name='to_split',
        ),
        migrations.AddField(
            model_name='turkanafossil',
            name='to_split',
            field=models.BooleanField(null=True),
        ),
    ]
