# Generated by Django 3.2.5 on 2021-12-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0079_auto_20211209_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='turkfossil',
            name='to_add',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='turkfossil',
            name='to_divide',
            field=models.BooleanField(null=True),
        ),
    ]
