# Generated by Django 3.2.5 on 2022-01-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0080_auto_20211209_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomen',
            name='generic_name',
            field=models.CharField(blank=True, help_text='The genus portion of the scientific name, e.g. Homo.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nomen',
            name='specific_epithet',
            field=models.CharField(blank=True, help_text='The trivial (species) portion of the scientific name, e.g. sapiens.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nomen',
            name='taxon_rank_group',
            field=models.CharField(blank=True, choices=[('species-group', 'species-group'), ('genus-group', 'genus-group'), ('family-group', 'family-group')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nomen',
            name='type_genus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nomen',
            name='type_species',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nomen',
            name='authorship',
            field=models.CharField(blank=True, help_text='The authorship of the naming publication, date included, e.g. King, 1864', max_length=255, null=True),
        ),
    ]
