# Generated by Django 3.2.5 on 2022-01-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0081_auto_20220106_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomen',
            name='nomenclatural_code',
            field=models.CharField(blank=True, choices=[('ICZN', 'ICZN'), ('ICBN', 'ICBN')], default='ICZN', max_length=255, null=True, verbose_name='Nom. Code'),
        ),
    ]
