# Generated by Django 3.2.5 on 2022-01-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0082_nomen_nomenclatural_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomen',
            name='taxon_rank_group',
            field=models.CharField(blank=True, choices=[('species-group', 'species-group'), ('genus-group', 'genus-group'), ('family-group', 'family-group')], default='species-group', max_length=255, null=True),
        ),
    ]
