# Generated by Django 3.2.5 on 2022-01-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0083_alter_nomen_taxon_rank_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomen',
            old_name='type_genus',
            new_name='type_taxon',
        ),
        migrations.RemoveField(
            model_name='nomen',
            name='type_species',
        ),
    ]
