# Generated by Django 3.2.5 on 2022-01-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0084_auto_20220106_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomen',
            old_name='name_reference',
            new_name='authorship_reference_obj',
        ),
    ]
