# Generated by Django 3.2.5 on 2022-01-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0085_rename_name_reference_nomen_authorship_reference_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomen',
            old_name='rank',
            new_name='taxon_rank_obj',
        ),
        migrations.AlterField(
            model_name='nomen',
            name='year',
            field=models.IntegerField(blank=True, help_text='The year the name was published in yyyy format.', null=True, verbose_name='Authorship Year'),
        ),
    ]
