# Generated by Django 3.2.5 on 2022-01-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0087_rename_zoobank_id_nomen_scientific_name_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomen',
            name='paratypes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
