# Generated by Django 3.2.5 on 2022-01-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0088_alter_nomen_paratypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomen',
            name='nomenclatural_status',
            field=models.CharField(blank=True, choices=[('unavailable', 'unavailable'), ('invalid', 'invalid'), ('suppressed', 'suppressed'), ('potentially_valid', 'potentially valid')], max_length=255, null=True, verbose_name='Nom. Status'),
        ),
    ]
