# Generated by Django 3.2.5 on 2022-01-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0089_alter_nomen_nomenclatural_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomen',
            name='is_established',
            field=models.BooleanField(default=False, verbose_name='Established'),
        ),
        migrations.AlterField(
            model_name='nomen',
            name='bc_status',
            field=models.CharField(blank=True, choices=[('valid', 'Valid'), ('invalid_gh', 'Invalid GH'), ('invalid_ga', 'Invalid GA'), ('invalid_gb', 'Invalid GB'), ('invalid_sh', 'Inavlid SH'), ('invalid_sm', 'Invalid SM'), ('invalid_sn', 'Invalid SN'), ('invalid_so', 'Inavlid SO'), ('suppressed', 'Suppressed')], max_length=255, null=True, verbose_name='BC Status'),
        ),
        migrations.AlterField(
            model_name='ttaxon',
            name='bc_status',
            field=models.CharField(blank=True, choices=[('valid', 'Valid'), ('invalid_gh', 'Invalid GH'), ('invalid_ga', 'Invalid GA'), ('invalid_gb', 'Invalid GB'), ('invalid_sh', 'Inavlid SH'), ('invalid_sm', 'Invalid SM'), ('invalid_sn', 'Invalid SN'), ('invalid_so', 'Inavlid SO'), ('suppressed', 'Suppressed')], max_length=255, null=True, verbose_name='Nom. Status'),
        ),
    ]
