# Generated by Django 3.2.12 on 2022-05-25 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0090_auto_20220118_2235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TurkanaFossil',
        ),
        migrations.AlterModelOptions(
            name='nomen',
            options={'ordering': ['name', 'year'], 'verbose_name': 'Nomen', 'verbose_name_plural': 'Nomina'},
        ),
    ]
