# Generated by Django 3.2.12 on 2022-06-12 18:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0091_auto_20220525_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomen',
            name='usage_remarks',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Remarks about frequency of usage of the name in the literature.', null=True, verbose_name='Usage Remarks'),
        ),
    ]
