# Generated by Django 3.2.12 on 2022-07-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0092_nomen_usage_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomen',
            name='status_remark',
            field=models.CharField(blank=True, choices=[('conditionally proposed', 'Conditionally proposed'), ('fictional', 'Fictional'), ('nomen nudum', 'Nomen nudum'), ('homonym', 'Homonym'), ('objective synonym', 'Objective synonym')], max_length=255, null=True),
        ),
    ]
