# Generated by Django 3.2.15 on 2022-10-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0097_auto_20221001_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomen',
            name='is_inquirenda',
            field=models.BooleanField(default=False, help_text='Nomina needing further investigation regarding their status are flagged as nomina inquirenda', verbose_name='Inquirenda'),
        ),
    ]
