# Generated by Django 3.2.15 on 2022-11-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0098_nomen_is_inquirenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='fossil',
            name='assigned_to',
            field=models.CharField(blank=True, choices=[('Denne Reed', 'DR'), ('Emily Raney', 'ER'), ('Jyhreh Johnson', 'JJ'), ('Harper Jackson', 'HJ'), ('Kennedy Knowlton', 'KK'), ('Nida Virabalin', 'NV'), ('Ashlynn Arzola', 'AA'), ('Nicholas Hartman', 'NH'), ('Jorge Ramirez Salinas', 'JRS')], max_length=255, null=True, verbose_name='Assigned'),
        ),
        migrations.AddField(
            model_name='fossil',
            name='verified_by',
            field=models.CharField(blank=True, choices=[('Denne Reed', 'DR'), ('Emily Raney', 'ER'), ('Jyhreh Johnson', 'JJ'), ('Harper Jackson', 'HJ'), ('Kennedy Knowlton', 'KK'), ('Nida Virabalin', 'NV'), ('Ashlynn Arzola', 'AA'), ('Nicholas Hartman', 'NH'), ('Jorge Ramirez Salinas', 'JRS')], max_length=255, null=True, verbose_name='Verified'),
        ),
        migrations.AddField(
            model_name='fossil',
            name='verified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='assigned_to',
            field=models.CharField(blank=True, choices=[('Denne Reed', 'DR'), ('Emily Raney', 'ER'), ('Jyhreh Johnson', 'JJ'), ('Harper Jackson', 'HJ'), ('Kennedy Knowlton', 'KK'), ('Nida Virabalin', 'NV'), ('Ashlynn Arzola', 'AA'), ('Nicholas Hartman', 'NH'), ('Jorge Ramirez Salinas', 'JRS')], max_length=255, null=True, verbose_name='Assigned'),
        ),
        migrations.AddField(
            model_name='site',
            name='verified_by',
            field=models.CharField(blank=True, choices=[('Denne Reed', 'DR'), ('Emily Raney', 'ER'), ('Jyhreh Johnson', 'JJ'), ('Harper Jackson', 'HJ'), ('Kennedy Knowlton', 'KK'), ('Nida Virabalin', 'NV'), ('Ashlynn Arzola', 'AA'), ('Nicholas Hartman', 'NH'), ('Jorge Ramirez Salinas', 'JRS')], max_length=255, null=True, verbose_name='Verified'),
        ),
        migrations.AddField(
            model_name='site',
            name='verified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomen',
            name='assigned_to',
            field=models.CharField(blank=True, choices=[('Denne Reed', 'DR'), ('Emily Raney', 'ER'), ('Jyhreh Johnson', 'JJ'), ('Harper Jackson', 'HJ'), ('Kennedy Knowlton', 'KK'), ('Nida Virabalin', 'NV'), ('Ashlynn Arzola', 'AA'), ('Nicholas Hartman', 'NH'), ('Jorge Ramirez Salinas', 'JRS')], max_length=255, null=True, verbose_name='Assigned'),
        ),
        migrations.AlterField(
            model_name='nomen',
            name='verified_by',
            field=models.CharField(blank=True, choices=[('Denne Reed', 'DR'), ('Emily Raney', 'ER'), ('Jyhreh Johnson', 'JJ'), ('Harper Jackson', 'HJ'), ('Kennedy Knowlton', 'KK'), ('Nida Virabalin', 'NV'), ('Ashlynn Arzola', 'AA'), ('Nicholas Hartman', 'NH'), ('Jorge Ramirez Salinas', 'JRS')], max_length=255, null=True, verbose_name='Verified'),
        ),
    ]
