# Generated by Django 3.2.15 on 2023-02-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0101_auto_20230215_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='fossilelement',
            name='anatomical_region',
            field=models.CharField(blank=True, choices=[('cranial', 'cranial'), ('appendicular', 'appendicular'), ('axial', 'axial')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fossilelement',
            name='completeness',
            field=models.CharField(blank=True, choices=[('complete', 'complete'), ('nearly complete', 'nearly complete'), ('fragment', 'fragment')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fossilelement',
            name='dental',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fossilelement',
            name='preserved_part',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fossilelement',
            name='uberon_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
