# Generated by Django 3.2.18 on 2023-05-18 20:57

from django.db import migrations

def update_fossil_year_discovered(apps, schema_editor):
    """
    Update the year_collected field with values from verbatim_year_discovered.
    :param apps:
    :param schema_editor:
    :return:
    """
    TurkFossil = apps.get_model('origins', 'TurkFossil')
    for turkfossil in TurkFossil.objects.all():
        if not turkfossil.year_collected:
            try:
                turkfossil.year_collected = int(turkfossil.verbatim_year_discovered)
            except ValueError:
                pass
            turkfossil.save()
class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0104_auto_20230518_0035'),
    ]

    operations = [
        migrations.RunPython(update_fossil_year_discovered, reverse_code=migrations.RunPython.noop),
    ]
