# Generated by Django 3.2.18 on 2023-05-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0105_auto_20230518_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fossil',
            name='verbatim_turkana_fossil',
        ),
    ]
