# Generated by Django 3.2.18 on 2023-05-29 22:29

from django.db import migrations

def update_fossils_leakey73a(apps, schema_editor):
    """
    Add Leakey 1973a to fossils mentioned in this reference
    :param apps:
    :param schema_editor:
    :return:
    """
    TurkFossil = apps.get_model('origins', 'TurkFossil')
    Publication = apps.get_model('publications', 'Publication')
    leakey73 = Publication.objects.get(citekey='Leakey1973a')
    for f in TurkFossil.objects.filter(verbatim_reference_first_mention='Leakey, 1973a'):
        f.references.add(leakey73)
        f.save()

class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0106_remove_fossil_verbatim_turkana_fossil'),
    ]

    operations = [
        migrations.RunPython(update_fossils_leakey73a, reverse_code=migrations.RunPython.noop),
    ]
