# Generated by Django 3.2.18 on 2023-05-30 00:38

from django.db import migrations

def update_fossil_references(apps, schema_editor):
    """
    Add references to fossils mentioned in this reference
    :param apps:
    :param schema_editor:
    :return:
    """
    TurkFossil = apps.get_model('origins', 'TurkFossil')
    Publication = apps.get_model('publications', 'Publication')
    List = apps.get_model('publications', 'List')
    tflist = List.objects.get(list='Turkana Fossils')
    citekey_lookup = {
        'Leakey, 1971': 'Leakey1971-gw',
        'Wood and Leakey, 2011': 'Wood2011',
        'Ward et al., 2001': 'Ward2001',
        'Howell, 1969': 'Howell1969',
        'Leakey, 1976': 'Leakey1976-dj',
        'Leakey et al., 1995': 'Leakey1995-ya',
        'Leakey 1972': 'Leakey1972-hu'  # This ref was updated in 0109_auto... but here the verbatim cite lacks a comma

    }

    for key in citekey_lookup:
        publication = Publication.objects.get(citekey=citekey_lookup[key])
        publication.lists.add(tflist)
        for f in TurkFossil.objects.filter(verbatim_reference_first_mention=key):
            f.references.add(publication)
            f.save()

class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0109_auto_20230530_0025'),
    ]

    operations = [
        migrations.RunPython(update_fossil_references, reverse_code=migrations.RunPython.noop),
    ]
