# Generated by Django 3.2.18 on 2023-05-30 01:45

from django.db import migrations

def update_fossil_references(apps, schema_editor):
    """
    Add references to fossils mentioned in this reference
    :param apps:
    :param schema_editor:
    :return:
    """
    TurkFossil = apps.get_model('origins', 'TurkFossil')
    Publication = apps.get_model('publications', 'Publication')
    List = apps.get_model('publications', 'List')
    tflist = List.objects.get(list='Turkana Fossils')
    citekey_lookup = {
        'Ward et al., 2013':'Ward2013',
        'Ward et al., 2020':'Ward2020',
        'Feibel et al., 1989':'Feibel1989-ks',
        'Grine et al., 2019':'Grine2019-dy',
        'Coppens, 1970':'Coppens1970',
        'Howell et al., 1987':'Howell1987',
        'Coppens, 1973a':'Coppens1973a',
        'Coppens, 1973b':'Coppens1973b',
        'Ward et al., 1999':'Ward1999',
        'Coppens, 1971':'Coppens1971',
        'Coppens, 1980':'Coppens1980',
        'Day et al., 1976':'Day1976'
    }

    for key in citekey_lookup:
        publication = Publication.objects.get(citekey=citekey_lookup[key])
        publication.lists.add(tflist)
        for f in TurkFossil.objects.filter(verbatim_reference_first_mention=key):
            f.references.add(publication)
            f.save()
class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0110_auto_20230530_0038'),
    ]

    operations = [
        migrations.RunPython(update_fossil_references, reverse_code=migrations.RunPython.noop),
    ]
