# Generated by Django 3.2.18 on 2023-05-30 05:51

from django.db import migrations
from origins.util import citekey_lookup
from collections import Counter

def update_fossil_references(apps, schema_editor):
    """
    Add references to fossils mentioned in this reference
    :param apps:
    :param schema_editor:
    :return:
    """
    TurkFossil = apps.get_model('origins', 'TurkFossil')
    Publication = apps.get_model('publications', 'Publication')
    List = apps.get_model('publications', 'List')
    tflist = List.objects.get(list='Turkana Fossils')
    pub_counts = Counter(TurkFossil.objects.values_list('verbatim_reference_description', flat=True))
    pub_counts_list = [p for p in pub_counts]
    for p in pub_counts_list:
        try:
            publication = Publication.objects.get(citekey=citekey_lookup[p])
            publication.lists.add(tflist)
            for f in TurkFossil.objects.filter(verbatim_reference_description=p):
                f.references.add(publication)
                f.save()
        except KeyError:
            pass
class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0116_auto_20230530_0530'),
    ]

    operations = [
        migrations.RunPython(update_fossil_references, reverse_code=migrations.RunPython.noop),
    ]
