# Generated by Django 3.2.18 on 2023-09-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0120_auto_20230829_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fossil',
            name='created',
        ),
        migrations.RemoveField(
            model_name='fossil',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='fossil',
            name='modified',
        ),
        migrations.AlterField(
            model_name='fossil',
            name='assigned_to',
            field=models.CharField(blank=True, choices=[('Denne Reed', 'DR'), ('Emily Raney', 'ER'), ('Jyhreh Johnson', 'JJ'), ('Harper Jackson', 'HJ'), ('Kennedy Knowlton', 'KK'), ('Nida Virabalin', 'NV'), ('Ashlynn Arzola', 'AA'), ('Nicholas Hartman', 'NH'), ('Jorge Ramirez Salinas', 'JRS'), ('Hayden Post', 'HP'), ('Mackenzie Murray', 'MM')], max_length=255, null=True, verbose_name='Assigned'),
        ),
        migrations.AlterField(
            model_name='fossil',
            name='verified_by',
            field=models.CharField(blank=True, choices=[('Denne Reed', 'DR'), ('Emily Raney', 'ER'), ('Jyhreh Johnson', 'JJ'), ('Harper Jackson', 'HJ'), ('Kennedy Knowlton', 'KK'), ('Nida Virabalin', 'NV'), ('Ashlynn Arzola', 'AA'), ('Nicholas Hartman', 'NH'), ('Jorge Ramirez Salinas', 'JRS'), ('Hayden Post', 'HP'), ('Mackenzie Murray', 'MM')], max_length=255, null=True, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='nomen',
            name='assigned_to',
            field=models.CharField(blank=True, choices=[('Denne Reed', 'DR'), ('Emily Raney', 'ER'), ('Jyhreh Johnson', 'JJ'), ('Harper Jackson', 'HJ'), ('Kennedy Knowlton', 'KK'), ('Nida Virabalin', 'NV'), ('Ashlynn Arzola', 'AA'), ('Nicholas Hartman', 'NH'), ('Jorge Ramirez Salinas', 'JRS'), ('Hayden Post', 'HP'), ('Mackenzie Murray', 'MM')], max_length=255, null=True, verbose_name='Assigned'),
        ),
        migrations.AlterField(
            model_name='nomen',
            name='verified_by',
            field=models.CharField(blank=True, choices=[('Denne Reed', 'DR'), ('Emily Raney', 'ER'), ('Jyhreh Johnson', 'JJ'), ('Harper Jackson', 'HJ'), ('Kennedy Knowlton', 'KK'), ('Nida Virabalin', 'NV'), ('Ashlynn Arzola', 'AA'), ('Nicholas Hartman', 'NH'), ('Jorge Ramirez Salinas', 'JRS'), ('Hayden Post', 'HP'), ('Mackenzie Murray', 'MM')], max_length=255, null=True, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='site',
            name='assigned_to',
            field=models.CharField(blank=True, choices=[('Denne Reed', 'DR'), ('Emily Raney', 'ER'), ('Jyhreh Johnson', 'JJ'), ('Harper Jackson', 'HJ'), ('Kennedy Knowlton', 'KK'), ('Nida Virabalin', 'NV'), ('Ashlynn Arzola', 'AA'), ('Nicholas Hartman', 'NH'), ('Jorge Ramirez Salinas', 'JRS'), ('Hayden Post', 'HP'), ('Mackenzie Murray', 'MM')], max_length=255, null=True, verbose_name='Assigned'),
        ),
        migrations.AlterField(
            model_name='site',
            name='verified_by',
            field=models.CharField(blank=True, choices=[('Denne Reed', 'DR'), ('Emily Raney', 'ER'), ('Jyhreh Johnson', 'JJ'), ('Harper Jackson', 'HJ'), ('Kennedy Knowlton', 'KK'), ('Nida Virabalin', 'NV'), ('Ashlynn Arzola', 'AA'), ('Nicholas Hartman', 'NH'), ('Jorge Ramirez Salinas', 'JRS'), ('Hayden Post', 'HP'), ('Mackenzie Murray', 'MM')], max_length=255, null=True, verbose_name='Verified'),
        ),
    ]
