# Generated by Django 3.2.18 on 2023-09-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0121_auto_20230902_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fossil',
            name='assigned_to',
            field=models.CharField(blank=True, choices=[('Denne Reed', 'Denne Reed'), ('Emily Raney', 'Emily Raney'), ('Jyhreh Johnson', 'Jyhreh Johnson'), ('Harper Jackson', 'Leo Jackson'), ('Kennedy Knowlton', 'Kennedy Knowlton'), ('Nida Virabalin', 'Nida Virabalin'), ('Ashlynn Arzola', 'Ashlynn Arzola'), ('Nicholas Hartman', 'Nicholas Hartman'), ('Jorge Ramirez Salinas', 'Jorge Ramirez Salinas'), ('Hayden Post', 'Hayden Post'), ('Mackenzie Murray', 'Mackenzie Murray'), ('Neena Landis', 'Neena Landis'), ('Madeleine Armstrong', 'Madeleine Armstrong')], max_length=255, null=True, verbose_name='Assigned'),
        ),
        migrations.AlterField(
            model_name='fossil',
            name='verified_by',
            field=models.CharField(blank=True, choices=[('Denne Reed', 'Denne Reed'), ('Emily Raney', 'Emily Raney'), ('Jyhreh Johnson', 'Jyhreh Johnson'), ('Harper Jackson', 'Leo Jackson'), ('Kennedy Knowlton', 'Kennedy Knowlton'), ('Nida Virabalin', 'Nida Virabalin'), ('Ashlynn Arzola', 'Ashlynn Arzola'), ('Nicholas Hartman', 'Nicholas Hartman'), ('Jorge Ramirez Salinas', 'Jorge Ramirez Salinas'), ('Hayden Post', 'Hayden Post'), ('Mackenzie Murray', 'Mackenzie Murray'), ('Neena Landis', 'Neena Landis'), ('Madeleine Armstrong', 'Madeleine Armstrong')], max_length=255, null=True, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='nomen',
            name='assigned_to',
            field=models.CharField(blank=True, choices=[('Denne Reed', 'Denne Reed'), ('Emily Raney', 'Emily Raney'), ('Jyhreh Johnson', 'Jyhreh Johnson'), ('Harper Jackson', 'Leo Jackson'), ('Kennedy Knowlton', 'Kennedy Knowlton'), ('Nida Virabalin', 'Nida Virabalin'), ('Ashlynn Arzola', 'Ashlynn Arzola'), ('Nicholas Hartman', 'Nicholas Hartman'), ('Jorge Ramirez Salinas', 'Jorge Ramirez Salinas'), ('Hayden Post', 'Hayden Post'), ('Mackenzie Murray', 'Mackenzie Murray'), ('Neena Landis', 'Neena Landis'), ('Madeleine Armstrong', 'Madeleine Armstrong')], max_length=255, null=True, verbose_name='Assigned'),
        ),
        migrations.AlterField(
            model_name='nomen',
            name='verified_by',
            field=models.CharField(blank=True, choices=[('Denne Reed', 'Denne Reed'), ('Emily Raney', 'Emily Raney'), ('Jyhreh Johnson', 'Jyhreh Johnson'), ('Harper Jackson', 'Leo Jackson'), ('Kennedy Knowlton', 'Kennedy Knowlton'), ('Nida Virabalin', 'Nida Virabalin'), ('Ashlynn Arzola', 'Ashlynn Arzola'), ('Nicholas Hartman', 'Nicholas Hartman'), ('Jorge Ramirez Salinas', 'Jorge Ramirez Salinas'), ('Hayden Post', 'Hayden Post'), ('Mackenzie Murray', 'Mackenzie Murray'), ('Neena Landis', 'Neena Landis'), ('Madeleine Armstrong', 'Madeleine Armstrong')], max_length=255, null=True, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='site',
            name='assigned_to',
            field=models.CharField(blank=True, choices=[('Denne Reed', 'Denne Reed'), ('Emily Raney', 'Emily Raney'), ('Jyhreh Johnson', 'Jyhreh Johnson'), ('Harper Jackson', 'Leo Jackson'), ('Kennedy Knowlton', 'Kennedy Knowlton'), ('Nida Virabalin', 'Nida Virabalin'), ('Ashlynn Arzola', 'Ashlynn Arzola'), ('Nicholas Hartman', 'Nicholas Hartman'), ('Jorge Ramirez Salinas', 'Jorge Ramirez Salinas'), ('Hayden Post', 'Hayden Post'), ('Mackenzie Murray', 'Mackenzie Murray'), ('Neena Landis', 'Neena Landis'), ('Madeleine Armstrong', 'Madeleine Armstrong')], max_length=255, null=True, verbose_name='Assigned'),
        ),
        migrations.AlterField(
            model_name='site',
            name='verified_by',
            field=models.CharField(blank=True, choices=[('Denne Reed', 'Denne Reed'), ('Emily Raney', 'Emily Raney'), ('Jyhreh Johnson', 'Jyhreh Johnson'), ('Harper Jackson', 'Leo Jackson'), ('Kennedy Knowlton', 'Kennedy Knowlton'), ('Nida Virabalin', 'Nida Virabalin'), ('Ashlynn Arzola', 'Ashlynn Arzola'), ('Nicholas Hartman', 'Nicholas Hartman'), ('Jorge Ramirez Salinas', 'Jorge Ramirez Salinas'), ('Hayden Post', 'Hayden Post'), ('Mackenzie Murray', 'Mackenzie Murray'), ('Neena Landis', 'Neena Landis'), ('Madeleine Armstrong', 'Madeleine Armstrong')], max_length=255, null=True, verbose_name='Verified'),
        ),
    ]
