# Generated by Django 3.2.18 on 2023-09-15 14:28

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0122_auto_20230909_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkeletalElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time this resource was first created.', verbose_name='Created')),
                ('date_last_modified', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time this resource was last altered.', verbose_name='Modified')),
                ('problem', models.BooleanField(default=False, help_text='Is there a problem with this record that needs attention?')),
                ('problem_comment', models.TextField(blank=True, help_text='Description of the problem.', null=True)),
                ('remarks', ckeditor.fields.RichTextField(blank=True, help_text='General remarks about this database record.', null=True, verbose_name='Record Remarks')),
                ('last_import', models.BooleanField(default=False)),
                ('uberon_id', models.CharField(blank=True, max_length=100, null=True)),
                ('anatomical_region', models.CharField(blank=True, choices=[('All', 'All'), ('Dental', 'Dental'), ('Cranial', 'Cranial'), ('Axial', 'Axial'), ('Appendicular', 'Appendicular')], max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
