# Generated by Django 3.2.18 on 2023-10-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0124_auto_20230915_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomen',
            name='is_chibanian',
            field=models.BooleanField(default=False, verbose_name='Chibanian'),
        ),
        migrations.AlterField(
            model_name='skeletalelement',
            name='anatomical_region',
            field=models.CharField(blank=True, choices=[('Entire', 'Entire'), ('Dental', 'Dental'), ('Cranial', 'Cranial'), ('Axial', 'Axial'), ('Appendicular', 'Appendicular')], max_length=100, null=True),
        ),
    ]
