# Generated by Django 3.2.18 on 2023-11-18 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0125_auto_20231006_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttaxon',
            name='nomen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='origins.nomen'),
        ),
    ]
