# Generated by Django 3.2.18 on 2023-11-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0127_auto_20231118_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttaxon',
            name='bc_status',
        ),
        migrations.RemoveField(
            model_name='ttaxon',
            name='nomenclatural_code',
        ),
        migrations.RemoveField(
            model_name='ttaxon',
            name='paratypes',
        ),
        migrations.RemoveField(
            model_name='ttaxon',
            name='type_specimen',
        ),
        migrations.RemoveField(
            model_name='ttaxon',
            name='type_status',
        ),
        migrations.RemoveField(
            model_name='ttaxon',
            name='year',
        ),
    ]
