# Generated by Django 3.2.12 on 2022-05-25 22:16

import ckeditor.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time this resource was first created.', verbose_name='Created')),
                ('date_last_modified', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time this resource was last altered.', verbose_name='Modified')),
                ('problem', models.BooleanField(default=False, help_text='Is there a problem with this record that needs attention?')),
                ('problem_comment', models.TextField(blank=True, help_text='Description of the problem.', null=True)),
                ('remarks', ckeditor.fields.RichTextField(blank=True, help_text='General remarks about this database record.', null=True, verbose_name='Record Remarks')),
                ('last_import', models.BooleanField(default=False)),
                ('georeference_remarks', models.TextField(blank=True, max_length=500, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('locality_id', models.CharField(blank=True, max_length=255, null=True)),
                ('collection_code', models.CharField(blank=True, max_length=10, null=True)),
                ('formation', models.CharField(blank=True, max_length=255, null=True)),
                ('member', models.CharField(blank=True, max_length=255, null=True)),
                ('bed', models.TextField(blank=True, null=True)),
                ('verbatim_age_ma', models.CharField(blank=True, max_length=255, null=True)),
                ('earliest_age_ma', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('latest_age_ma', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('age_protocol', models.CharField(blank=True, max_length=255, null=True)),
                ('year_established', models.IntegerField(blank=True, null=True)),
                ('dimension_ew', models.CharField(blank=True, max_length=255, null=True)),
                ('dimension_ns', models.CharField(blank=True, max_length=255, null=True)),
                ('locality_description', models.TextField(blank=True, null=True)),
                ('locality_boundary_east', models.CharField(blank=True, max_length=255, null=True)),
                ('locality_boundary_north', models.CharField(blank=True, max_length=255, null=True)),
                ('locality_boundary_south', models.CharField(blank=True, max_length=255, null=True)),
                ('locality_boundary_west', models.CharField(blank=True, max_length=255, null=True)),
                ('macrobotanical_evidence', models.CharField(blank=True, max_length=255, null=True)),
                ('archaeological_evidence', models.CharField(blank=True, max_length=255, null=True)),
                ('uncollected_taxa', models.CharField(blank=True, max_length=255, null=True)),
                ('archaeology_present', models.BooleanField(blank=True, null=True)),
                ('macrobotanical_present', models.BooleanField(blank=True, null=True)),
                ('elevation', models.IntegerField(blank=True, null=True)),
                ('georeference_protocol', models.CharField(blank=True, max_length=255, null=True)),
                ('verbatim_row_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Locality',
                'verbose_name_plural': 'Localities',
                'ordering': ['locality_id'],
            },
        ),
    ]
