# Generated by Django 3.2.5 on 2021-10-27 20:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sermar', '0002_locality_roost_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time this resource was first created.', verbose_name='Created')),
                ('date_last_modified', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time this resource was last altered.', verbose_name='Modified')),
                ('problem', models.BooleanField(default=False, help_text='Is there a problem with this record that needs attention?')),
                ('problem_comment', models.TextField(blank=True, help_text='Description of the problem.', max_length=255, null=True)),
                ('remarks', ckeditor.fields.RichTextField(blank=True, help_text='General remarks about this database record.', null=True, verbose_name='Record Remarks')),
                ('last_import', models.BooleanField(default=False)),
                ('coll_id', models.IntegerField(blank=True, null=True)),
                ('roost_id', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('specimen_loc', models.CharField(blank=True, max_length=256, null=True)),
                ('spec_start', models.IntegerField(blank=True, null=True)),
                ('spec_end', models.IntegerField(blank=True, null=True)),
                ('sample_size', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(blank=True, max_length=256, null=True)),
                ('comments', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bags', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sermar.locality')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
