# Generated by Django 3.2.5 on 2021-10-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermar', '0003_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='disposition',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
