# Generated by Django 3.2.5 on 2021-10-31 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermar', '0005_biology_occurrence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biology',
            options={},
        ),
    ]
