# Generated by Django 3.2.5 on 2021-11-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermar', '0006_alter_biology_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='collection_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Collection Code'),
        ),
    ]
