# Generated by Django 3.2.5 on 2021-11-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermar', '0007_alter_occurrence_collection_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biology',
            options={'verbose_name': 'Biology Occurrence', 'verbose_name_plural': 'Biology Occurrences'},
        ),
    ]
