# Generated by Django 3.2.5 on 2021-11-01 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sermar', '0008_alter_biology_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sermar.collection'),
        ),
    ]
