# Generated by Django 3.2.5 on 2021-11-01 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermar', '0009_occurrence_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='coll_id',
            new_name='collection_code',
        ),
    ]
