# Generated by Django 3.2.5 on 2021-11-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermar', '0010_rename_coll_id_collection_collection_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='accumulating_agent',
            field=models.CharField(blank=True, choices=[('Tyto alba', 'Tyto alba'), ('Likely Tyto alba', 'Likely Tyto alba'), ('Bubo africanus', 'Bubo africanus'), ('Likely Bubo africanus', 'Likely Bubo africanus'), ('Unknown', 'Unknown')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Collected'),
        ),
    ]
