# Generated by Django 3.2.5 on 2021-11-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermar', '0011_auto_20211101_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='accumulating_agent',
            field=models.CharField(blank=True, choices=[('Tyto alba', 'Tyto alba'), ('Likely Tyto alba', 'Likely Tyto alba'), ('Bubo africanus', 'Bubo africanus'), ('Likely Bubo africanus', 'Likely Bubo africanus'), ('Unknown', 'Unknown')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='basis_of_record',
            field=models.CharField(blank=True, choices=[('FossilSpecimen', 'Fossil'), ('PreservedSpecimen', 'Preserved Specimen'), ('HumanObservation', 'Observation')], max_length=50, verbose_name='Basis of Record'),
        ),
    ]
