# Generated by Django 3.2.5 on 2021-11-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermar', '0012_auto_20211108_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='protected_area',
            field=models.CharField(blank=True, choices=[('Serengeti National Park', 'Serengeti National Park'), ('Ngorongoro Conservation Area', 'Ngorongoro Conservation Area'), ('Loliondo Game Control Area', 'Loliondo Game Control Area'), ('Maswa Game Reserve', 'Maswa Game Reserve'), ('Koyaki Group Ranch', 'Koyaki Group Ranch'), ('Olkinyei Group Ranch', 'Olkinyei Group Ranch'), ('Masai Mara National Park', 'Masai Mara National Park'), ('Siana Group Ranch', 'Siana Group Ranch'), ('Grumeti Game Reserve', 'Grumeti Game Reserve'), ('Ol Choro Orogwa Group Ranch', 'Ol Choro Orogwa Group Ranch'), ('Lemek Group Ranch', 'Lemek Group Ranch'), ('Ikorongo Game Reserve', 'Ikorongo Game Reserve')], max_length=255, null=True),
        ),
    ]
