# Generated by Django 3.2.5 on 2021-11-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermar', '0014_alter_locality_protected_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='problem_comment',
            field=models.TextField(blank=True, help_text='Description of the problem.', null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='problem_comment',
            field=models.TextField(blank=True, help_text='Description of the problem.', null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='problem_comment',
            field=models.TextField(blank=True, help_text='Description of the problem.', null=True),
        ),
    ]
