# Generated by Django 3.2.18 on 2023-10-27 15:32

from django.db import migrations
import pandas as pd
from django.conf import settings
import os

source_path = os.path.join(settings.PROJECT_ROOT, 'sermar','data','morphotypes.xlsx')

def import_data(source=source_path):
    xls = pd.ExcelFile(source)
    df = xls.parse(xls.sheet_names[0])
    return df

def import_morphotypes(apps, schema_editor):
    data = import_data()
    Morphotype = apps.get_model('sermar', 'Morphotype')
    for i in data.index:
        morph_id = data.loc[i].morph_id
        morph_name = data.loc[i].morph_name
        order_id = data.loc[i].order_id
        none_strings = ('',' ', 'nan')
        if data.loc[i].species1 not in none_strings:
            species1_id = data.loc[i].species1
        else: species1_id = None

        if data.loc[i].species2 not in none_strings:
            species2_id = data.loc[i].species2
        else: species2_id = None

        if data.loc[i].species3 not in none_strings:
            species3_id = data.loc[i].species3
        else: species3_id = None

        if data.loc[i].species4 not in none_strings:
            species4_id = data.loc[i].species4
        else: species4_id = None

        analysis_id = data.loc[i].analysis_id
        remarks = data.loc[i].remarks
        new_morphotype = Morphotype(morph_id=morph_id,
                                    name=morph_name,
                                    order_id=order_id,
                                    species1_id=species1_id,
                                    species2_id=species2_id,
                                    species3_id=species3_id,
                                    species4_id=species4_id,
                                    analysis_id=analysis_id,
                                    remarks=remarks,)
        new_morphotype.save()
class Migration(migrations.Migration):

    dependencies = [
        ('sermar', '0016_morphotype'),
    ]

    operations = [
        migrations.RunPython(import_morphotypes, reverse_code=migrations.RunPython.noop),
    ]
