# Generated by Django 3.2.18 on 2023-10-27 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sermar', '0017_auto_20231027_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biology',
            old_name='morphotype_id',
            new_name='verbatim_morphotype_id',
        ),
        migrations.AddField(
            model_name='biology',
            name='morphotype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sermar.morphotype'),
        ),
    ]
