# Generated by Django 3.2.18 on 2023-10-27 16:21

from django.db import migrations

def update_morphotypes(apps, schema_editor):
    Biology = apps.get_model('sermar', 'Biology')
    Morphotype = apps.get_model('sermar', 'Morphotype')
    for b in Biology.objects.all():
        try:
            b.morphotype = Morphotype.objects.get(morph_id=b.verbatim_morphotype_id)
            b.save()
        except:
            pass
class Migration(migrations.Migration):

    dependencies = [
        ('sermar', '0018_auto_20231027_1616'),
    ]

    operations = [
        migrations.RunPython(update_morphotypes, reverse_code=migrations.RunPython.noop),
    ]
