# Generated by Django 3.2.18 on 2023-10-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermar', '0020_specimenphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='catalog_number',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='ranked',
        ),
    ]
