# Generated by Django 3.2.12 on 2022-02-25 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fossil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_number', models.CharField(max_length=200)),
                ('ut_catalog_id', models.CharField(blank=True, max_length=200, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=200, null=True)),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
                ('is_type_specimen', models.BooleanField(default=False, verbose_name='Type Specimen')),
                ('ut_storage_location', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Primate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_number', models.CharField(max_length=200)),
                ('ut_catalog_id', models.CharField(blank=True, max_length=200, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=200, null=True)),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
                ('ut_storage_location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fossils', verbose_name='Image')),
                ('description', models.TextField(blank=True, null=True)),
                ('default_image', models.BooleanField(default=False)),
                ('fossil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utcasts.fossil')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'managed': True,
            },
        ),
    ]
