# Generated by Django 3.2.23 on 2023-12-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0002_auto_20211127_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='related_catalog_items',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Related Catalog Items'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='verbatim_kml_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
