# Generated by Django 3.2.5 on 2021-11-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlp', '0003_auto_20210112_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='basis_of_record',
            field=models.CharField(blank=True, choices=[('FossilSpecimen', 'Fossil'), ('PreservedSpecimen', 'Preserved Specimen'), ('HumanObservation', 'Observation')], max_length=50, verbose_name='Basis of Record'),
        ),
    ]
