# Generated by Django 2.2.24 on 2021-07-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('pages', '0025_auto_20210327_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='originssiteindexpagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='originssiteindexpagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='originssiteindexpagerelatedlink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='originssitepage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='originssitepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='originssitepage',
            name='site',
        ),
        migrations.RemoveField(
            model_name='originssitepage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='originssitepagecarouselitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='originssitepagecarouselitem',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='originssitepagecarouselitem',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='originssitepagecarouselitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='originssitepagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='originssitepagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='originssitepagerelatedlink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='originssitepagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='originssitepagetag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='OriginsSiteIndexPage',
        ),
        migrations.DeleteModel(
            name='OriginsSiteIndexPageRelatedLink',
        ),
        migrations.DeleteModel(
            name='OriginsSitePage',
        ),
        migrations.DeleteModel(
            name='OriginsSitePageCarouselItem',
        ),
        migrations.DeleteModel(
            name='OriginsSitePageRelatedLink',
        ),
        migrations.DeleteModel(
            name='OriginsSitePageTag',
        ),
    ]
