# Generated by Django 3.2.15 on 2022-10-01 18:53

from django.db import migrations
from datetime import date


def update_locality_dates(apps, schema_editor):
    Occurrence = apps.get_model('gdb', 'Occurrence')
    new_date = date.fromisoformat('2010-09-02')
    ids = ['13191', '13190', '13189', '13188', '13187', '13186', '13185', '13184', '13183', '13182', '13181', '13180',
           '13179', '13178', '13177', '13176', '13175', '13174', '13173', '13172', '13171', '13170', '13169', '13168',
           '13167', '13166', '13165', '13164', '13163', '13162', '13161', '13160', '13159', '13158', '13157', '13156',
           '13155', '13154', '13153', '13152', '13151', '13150', '13149', '13148', '13147', '13146', '13145', '13144',
           '13143', '13142', '13141', '13140', '13139', '13138', '13137', '13136', '13135', '13134', '13133', '13132',
           '13131', '13130', '13129', '13128', '13127', '13126', '13125', '13124', '13123', '13122', '13121', '13120',
           '13119', '13118', '13117', '13116', '13115', '13114', '13113', '13112', '13111', '13110']
    # update 82 specimens with a new collection date of 2 Sept. 2010
    Occurrence.objects.filter(catalog_number__in=ids).update(date_collected=new_date)


class Migration(migrations.Migration):

    dependencies = [
        ('gdb', '0003_auto_20211127_2058'),
    ]

    operations = [
        migrations.RunPython(update_locality_dates)
    ]
