# Generated by Django 3.2.15 on 2023-02-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdb', '0005_auto_20221005_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='map_100',
            field=models.CharField(blank=True, choices=[('Red Desert', 'Red Desert'), ('South Pass', 'South Pass')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='map_24',
            field=models.CharField(blank=True, choices=[('Antelope Flats', 'Antelope Flats'), ('Bitter Creek', 'Bitter Creek'), ('Bitter Creek NE', 'Bitter Creek NE'), ('Bitter Creek NW', 'Bitter Creek NW'), ('Black Rock Flat West', 'Black Rock Flat West'), ('Black Rock North', 'Black Rock North'), ('Desert Springs', 'Desert Springs'), ('Freighter Gap', 'Freighter Gap'), ('JO Dugway', 'JO Dugway'), ('Joe Hay Rim', 'Joe Hay Rim'), ('Luman Rim', 'Luman Rim'), ('Red Desert NW', 'Red Desert NW'), ('Red Desert SW', 'Red Desert SW'), ('Red Lake SW', 'Red Lake SW'), ('Sand Butte NW', 'Sand Butte NW'), ('Steamboat Mountain', 'Steamboat Mountain'), ('Table Rock', 'Table Rock'), ('The Pinnacles', 'The Pinnacles'), ('Tipton', 'Tipton'), ('Twelve Mile Well', 'Twelve Mile Well')], max_length=100, null=True),
        ),
    ]
