# Generated by Django 3.2.15 on 2023-02-21 23:38

from django.db import migrations
from django.db.models import F
from gdb.ontologies import *
south_pass_list = [freighter_gap, joe_hay_rim, luman_rim, the_pinnacles]
red_desert_list = [antelope_flats, bitter_creak, bitter_creak_ne, bitter_creak_nw, black_rock_flat_w,
                   black_rock_n, desert_springs, jo_dugway, red_desert_nw, red_desert_sw, red_lake_sw,
                   sand_butte_nw, steamboat_mountain, table_rock, tipton, twelve_mile_well]


def update_localities(apps, schema_editor):
    Locality = apps.get_model('gdb', 'Locality')
    Locality.objects.all().update(map_24=F('quad_sheet'))  # copy quad_sheet to map_24
    localities = Locality.objects.all()
    for l in localities:
        if l.map_24 in south_pass_list:
            l.map_100 = south_pass
        elif l.map_24 in red_desert_list:
            l.map_100 = red_desert
        else:
            print(f'map mismatch for id:{l.pk}, value:{l.quad_sheet}')
        l.save()
class Migration(migrations.Migration):

    dependencies = [
        ('gdb', '0006_auto_20230221_2334'),
    ]

    operations = [
        migrations.RunPython(update_localities, reverse_code=migrations.RunPython.noop)
    ]
