# Generated by Django 3.2.18 on 2023-05-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdb', '0007_auto_20230221_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='cm_locality_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
