# Generated by Django 3.2.18 on 2023-05-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdb', '0008_alter_locality_cm_locality_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='cm_locality_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='cm_catalog_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
