# Generated by Django 2.2.13 on 2020-12-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geologicalcontext',
            name='best_age',
        ),
        migrations.RemoveField(
            model_name='geologicalcontext',
            name='geological_bed',
        ),
        migrations.RemoveField(
            model_name='geologicalcontext',
            name='geological_formation',
        ),
        migrations.RemoveField(
            model_name='geologicalcontext',
            name='geological_member',
        ),
        migrations.RemoveField(
            model_name='geologicalcontext',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='geologicalcontext',
            name='min_age',
        ),
        migrations.RemoveField(
            model_name='geologicalcontext',
            name='older_interval',
        ),
        migrations.RemoveField(
            model_name='geologicalcontext',
            name='younger_interval',
        ),
        migrations.AddField(
            model_name='geologicalcontext',
            name='formation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='geologicalcontext',
            name='georeference_remarks',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='geologicalcontext',
            name='member',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
