# Generated by Django 2.2.13 on 2021-02-05 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcavatedAggregate',
            fields=[
                ('excavationoccurrence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psr.ExcavationOccurrence')),
                ('screen_size', models.CharField(blank=True, max_length=255, null=True)),
                ('burning', models.BooleanField(default=False)),
                ('bone', models.BooleanField(default=False)),
                ('microfauna', models.BooleanField(default=False)),
                ('pebbles', models.BooleanField(default=False)),
                ('smallplatforms', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('smalldebris', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('tinyplatforms', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('tinydebris', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('counts', models.IntegerField(blank=True, null=True)),
                ('weights', models.IntegerField(blank=True, null=True)),
                ('bull_find_remarks', models.TextField(blank=True, max_length=64000, null=True)),
            ],
            options={
                'verbose_name': 'PSR Excavated Bulk Find',
                'verbose_name_plural': 'PSR Excavated Bulk Finds',
            },
            bases=('psr.excavationoccurrence',),
        ),
        migrations.CreateModel(
            name='ExcavatedArchaeology',
            fields=[
                ('excavationoccurrence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psr.ExcavationOccurrence')),
                ('archaeology_type', models.CharField(blank=True, max_length=255, null=True)),
                ('period', models.CharField(blank=True, max_length=255, null=True)),
                ('archaeology_preparation', models.CharField(blank=True, max_length=255, null=True)),
                ('archaeology_remarks', models.TextField(blank=True, max_length=64000, null=True)),
                ('length_mm', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('width_mm', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('thick_mm', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('archaeology_notes', models.TextField(blank=True, max_length=64000, null=True)),
            ],
            options={
                'verbose_name': 'PSR Excavated Archaeology',
                'verbose_name_plural': 'PSR Excavated Archaeology',
            },
            bases=('psr.excavationoccurrence',),
        ),
        migrations.CreateModel(
            name='ExcavatedGeology',
            fields=[
                ('excavationoccurrence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psr.ExcavationOccurrence')),
                ('geology_type', models.CharField(blank=True, max_length=255, null=True)),
                ('dip', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('strike', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('texture', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'PSR Excavated Geology',
                'verbose_name_plural': 'PSR Excavated Geology',
            },
            bases=('psr.excavationoccurrence',),
        ),
        migrations.AlterModelOptions(
            name='aggregate',
            options={'verbose_name': 'PSR Survey Bulk Find', 'verbose_name_plural': 'PSR Survey Bulk Finds'},
        ),
        migrations.AddField(
            model_name='excavationoccurrence',
            name='item_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Item Type'),
        ),
        migrations.CreateModel(
            name='ExcavatedBone',
            fields=[
                ('excavatedarchaeology_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psr.ExcavatedArchaeology')),
                ('cutmarks', models.BooleanField(default=False)),
                ('burning', models.BooleanField(default=False)),
                ('part', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'PSR Excavated Archaeological Fauna',
                'verbose_name_plural': 'PSR Excavated Archaeological Fauna',
            },
            bases=('psr.excavatedarchaeology',),
        ),
        migrations.CreateModel(
            name='ExcavatedCeramic',
            fields=[
                ('excavatedarchaeology_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psr.ExcavatedArchaeology')),
                ('ceramic_type', models.CharField(blank=True, max_length=255, null=True)),
                ('decorated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'PSR Excavated Ceramic',
                'verbose_name_plural': 'PSR Excavated Ceramics',
            },
            bases=('psr.excavatedarchaeology',),
        ),
        migrations.CreateModel(
            name='ExcavatedLithic',
            fields=[
                ('excavatedarchaeology_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psr.ExcavatedArchaeology')),
                ('dataclass', models.CharField(blank=True, max_length=255, null=True)),
                ('fbtype', models.SmallIntegerField(blank=True, null=True)),
                ('form', models.CharField(blank=True, max_length=255, null=True)),
                ('technique', models.CharField(blank=True, max_length=255, null=True)),
                ('cortex', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('coretype', models.CharField(blank=True, max_length=255, null=True)),
                ('platsurf', models.CharField(blank=True, max_length=255, null=True)),
                ('scarmorph', models.CharField(blank=True, max_length=255, null=True)),
                ('edgedamage', models.CharField(blank=True, max_length=255, null=True)),
                ('platwidth', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('platthick', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('epa', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('scarlength', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
            ],
            options={
                'verbose_name': 'PSR Excavated Lithic',
                'verbose_name_plural': 'PSR Excavated Lithics',
            },
            bases=('psr.excavatedarchaeology',),
        ),
        migrations.CreateModel(
            name='ExcavatedBiology',
            fields=[
                ('excavationoccurrence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psr.ExcavationOccurrence')),
                ('biology_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sex')),
                ('life_stage', models.CharField(blank=True, max_length=50, null=True, verbose_name='Life Stage')),
                ('size_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Size Class')),
                ('verbatim_taxon', models.CharField(blank=True, max_length=1024, null=True)),
                ('verbatim_identification_qualifier', models.CharField(blank=True, max_length=255, null=True)),
                ('taxonomy_remarks', models.TextField(blank=True, max_length=500, null=True)),
                ('type_status', models.CharField(blank=True, max_length=50, null=True)),
                ('fauna_notes', models.TextField(blank=True, max_length=64000, null=True)),
                ('identification_qualifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excv_bio_occurrences', to='psr.IdentificationQualifier')),
                ('taxon', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='excv_bio_occurrences', to='psr.Taxon')),
            ],
            options={
                'verbose_name': 'PSR Excavated Biology',
                'verbose_name_plural': 'PSR Excavated Biology',
            },
            bases=('psr.excavationoccurrence',),
        ),
    ]
