# Generated by Django 2.2.13 on 2020-12-04 20:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='point',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=-1),
        ),
    ]
