# Generated by Django 2.2.13 on 2021-02-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0002_auto_20210205_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bone',
            options={'verbose_name': 'PSR Survey Archaeological Fauna', 'verbose_name_plural': 'PSR Survey Archaeological Fauna'},
        ),
        migrations.AlterModelOptions(
            name='ceramic',
            options={'verbose_name': 'PSR Survey Ceramic', 'verbose_name_plural': 'PSR Survey Ceramics'},
        ),
        migrations.AlterModelOptions(
            name='geologicalcontext',
            options={'ordering': ['context_number'], 'verbose_name': 'Geological Context', 'verbose_name_plural': 'Geological Contexts'},
        ),
        migrations.AlterModelOptions(
            name='lithic',
            options={'verbose_name': 'PSR Survey Lithic', 'verbose_name_plural': 'PSR Survey Lithics'},
        ),
        migrations.RemoveField(
            model_name='aggregate',
            name='weights',
        ),
        migrations.RemoveField(
            model_name='archaeology',
            name='archaeology_preparation',
        ),
        migrations.RemoveField(
            model_name='excavatedaggregate',
            name='weights',
        ),
        migrations.RemoveField(
            model_name='excavatedgeology',
            name='dip',
        ),
        migrations.RemoveField(
            model_name='excavatedgeology',
            name='strike',
        ),
        migrations.RemoveField(
            model_name='excavatedlithic',
            name='fbtype',
        ),
        migrations.RemoveField(
            model_name='geologicalcontext',
            name='analytical_unit_1',
        ),
        migrations.RemoveField(
            model_name='geologicalcontext',
            name='analytical_unit_2',
        ),
        migrations.RemoveField(
            model_name='geologicalcontext',
            name='analytical_unit_3',
        ),
        migrations.RemoveField(
            model_name='geologicalcontext',
            name='analytical_unit_found',
        ),
        migrations.RemoveField(
            model_name='geologicalcontext',
            name='analytical_unit_likely',
        ),
        migrations.RemoveField(
            model_name='geologicalcontext',
            name='analytical_unit_simplified',
        ),
        migrations.RemoveField(
            model_name='geologicalcontext',
            name='surface_modification',
        ),
        migrations.RemoveField(
            model_name='geologicalcontext',
            name='weathering',
        ),
        migrations.RemoveField(
            model_name='lithic',
            name='fbtype',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='drainage_region',
        ),
        migrations.AddField(
            model_name='aggregate',
            name='molluscs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='excavatedaggregate',
            name='molluscs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='alteration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='bifsupport',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='biftype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='extplat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='lentothick',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='lentowid',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='lip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='midthick',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='midwidth',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='pointimpact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='raw_material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='raw_material1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='retedge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='roet1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='roew1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='roew3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='tipwidth',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='tqthick',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='tqwidth',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='type1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='type2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lithic',
            name='alteration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lithic',
            name='bifsupport',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lithic',
            name='biftype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lithic',
            name='extplat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lithic',
            name='lentothick',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='lithic',
            name='lentowid',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='lithic',
            name='lip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lithic',
            name='midthick',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='lithic',
            name='midwidth',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='lithic',
            name='pointimpact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lithic',
            name='raw_material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lithic',
            name='raw_material1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lithic',
            name='retedge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lithic',
            name='roet1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lithic',
            name='roew1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lithic',
            name='roew3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lithic',
            name='tipwidth',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='lithic',
            name='tqthick',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='lithic',
            name='tqwidth',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='lithic',
            name='type1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lithic',
            name='type2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
