# Generated by Django 2.2.13 on 2021-02-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0003_auto_20210209_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lithic',
            name='roet1',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AlterField(
            model_name='lithic',
            name='roew1',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AlterField(
            model_name='lithic',
            name='roew3',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
    ]
