# Generated by Django 2.2.13 on 2021-01-27 19:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0004_auto_20210127_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excavationoccurrence',
            name='point',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, dim=3, null=True, srid=4326),
        ),
    ]
