# Generated by Django 2.2.13 on 2020-08-10 19:07

import ckeditor.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0005_auto_20200806_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeologicalContext',
            fields=[
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time this resource was first created.', verbose_name='Created')),
                ('problem', models.BooleanField(default=False, help_text='Is there a problem with this record that needs attention?')),
                ('problem_comment', models.TextField(blank=True, help_text='Description of the problem.', max_length=255, null=True)),
                ('remarks', ckeditor.fields.RichTextField(blank=True, help_text='General remarks about this database record.', null=True, verbose_name='Record Remarks')),
                ('last_import', models.BooleanField(default=False)),
                ('geological_formation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Formation')),
                ('geological_member', models.CharField(blank=True, max_length=50, null=True, verbose_name='Member')),
                ('geological_bed', models.CharField(blank=True, max_length=50, null=True)),
                ('older_interval', models.CharField(blank=True, max_length=50, null=True)),
                ('younger_interval', models.CharField(blank=True, max_length=50, null=True)),
                ('max_age', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('min_age', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('best_age', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=255, null=True)),
                ('context_type', models.CharField(blank=True, max_length=255, null=True)),
                ('context_number', models.IntegerField(blank=True, null=True)),
                ('collection_code', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('stratigraphic_section', models.CharField(blank=True, max_length=50, null=True)),
                ('stratigraphic_formation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Formation')),
                ('stratigraphic_member', models.CharField(blank=True, max_length=255, null=True, verbose_name='Member')),
                ('upper_limit_in_section', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('lower_limit_in_section', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('analytical_unit_1', models.CharField(blank=True, max_length=255, null=True)),
                ('analytical_unit_2', models.CharField(blank=True, max_length=255, null=True)),
                ('analytical_unit_3', models.CharField(blank=True, max_length=255, null=True)),
                ('analytical_unit_found', models.CharField(blank=True, max_length=255, null=True)),
                ('analytical_unit_likely', models.CharField(blank=True, max_length=255, null=True)),
                ('analytical_unit_simplified', models.CharField(blank=True, max_length=255, null=True)),
                ('in_situ', models.BooleanField(default=False)),
                ('ranked', models.BooleanField(default=False)),
                ('weathering', models.SmallIntegerField(blank=True, null=True)),
                ('surface_modification', models.CharField(blank=True, max_length=255, null=True, verbose_name='Surface Mod')),
                ('dip', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('strike', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('texture', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('slope_character', models.TextField(blank=True, max_length=64000, null=True)),
                ('sediment_presence', models.BooleanField(default=False)),
                ('sediment_character', models.TextField(blank=True, max_length=64000, null=True)),
                ('cave_mouth_character', models.TextField(blank=True, max_length=64000, null=True)),
                ('rockfall_character', models.TextField(blank=True, max_length=64000, null=True)),
                ('speleothem_character', models.TextField(blank=True, max_length=64000, null=True)),
                ('context_remarks', models.TextField(blank=True, max_length=500, null=True, verbose_name='Context Remarks')),
                ('error_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('date_last_modified', models.DateTimeField(auto_now=True, verbose_name='Date Last Modified')),
            ],
            options={
                'verbose_name': 'PSR Geological Context',
                'verbose_name_plural': 'PSR Geological Contexts',
                'ordering': ['context_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='occurrence',
            options={'ordering': ['collection_code', 'geological_context', 'item_number', 'item_part'], 'verbose_name': 'PSR Occurrence', 'verbose_name_plural': 'PSR Occurrences'},
        ),
        migrations.RemoveField(
            model_name='excavationunit',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='analytical_unit_1',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='analytical_unit_2',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='analytical_unit_3',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='analytical_unit_found',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='analytical_unit_likely',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='analytical_unit_simplified',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='geology_remarks',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='in_situ',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='ranked',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='stratigraphic_formation',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='stratigraphic_member',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='surface_modification',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='weathering',
        ),
        migrations.DeleteModel(
            name='Cave',
        ),
        migrations.DeleteModel(
            name='Locality',
        ),
        migrations.AddField(
            model_name='excavationunit',
            name='geological_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psr.GeologicalContext'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='geological_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psr.GeologicalContext'),
        ),
    ]
