# Generated by Django 2.2.13 on 2021-01-28 15:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0005_auto_20210127_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excavationoccurrence',
            options={'verbose_name': 'PSR Excavated Occurrence', 'verbose_name_plural': 'PSR Excavated Occurrences'},
        ),
        migrations.AlterModelOptions(
            name='occurrence',
            options={'ordering': ['collection_code', 'geological_context', 'item_number', 'item_part'], 'verbose_name': 'PSR Survey Occurrence', 'verbose_name_plural': 'PSR Survey Occurrences'},
        ),
        migrations.AlterField(
            model_name='excavationoccurrence',
            name='point',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, dim=3, null=True, srid=-1),
        ),
    ]
