# Generated by Django 2.2.13 on 2021-02-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0005_auto_20210209_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geologicalcontext',
            old_name='amount_coarse_components',
            new_name='loess_amount_coarse_components',
        ),
        migrations.RenameField(
            model_name='geologicalcontext',
            old_name='landscape_position',
            new_name='loess_landscape_position',
        ),
        migrations.RenameField(
            model_name='geologicalcontext',
            old_name='max_thickness',
            new_name='loess_max_thickness',
        ),
        migrations.RenameField(
            model_name='geologicalcontext',
            old_name='mean_thickness',
            new_name='loess_mean_thickness',
        ),
        migrations.RenameField(
            model_name='geologicalcontext',
            old_name='number_coarse_layers',
            new_name='loess_number_coarse_layers',
        ),
        migrations.RenameField(
            model_name='geologicalcontext',
            old_name='number_cultural_horizons',
            new_name='loess_number_cultural_horizons',
        ),
        migrations.RenameField(
            model_name='geologicalcontext',
            old_name='number_sediment_layers',
            new_name='loess_number_sediment_layers',
        ),
        migrations.RenameField(
            model_name='geologicalcontext',
            old_name='number_soil_horizons',
            new_name='loess_number_soil_horizons',
        ),
        migrations.RenameField(
            model_name='geologicalcontext',
            old_name='presence_coarse_components',
            new_name='loess_presence_coarse_components',
        ),
        migrations.RenameField(
            model_name='geologicalcontext',
            old_name='presence_vertical_profile',
            new_name='loess_presence_vertical_profile',
        ),
        migrations.RenameField(
            model_name='geologicalcontext',
            old_name='surface_inclination',
            new_name='loess_surface_inclination',
        ),
    ]
