# Generated by Django 2.2.13 on 2020-09-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0006_auto_20200810_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='geologicalcontext',
            name='amount_coarse_components',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='geologicalcontext',
            name='landscape_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='geologicalcontext',
            name='max_thickness',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='geologicalcontext',
            name='mean_thickness',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='geologicalcontext',
            name='number_coarse_layers',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geologicalcontext',
            name='number_cultural_horizons',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geologicalcontext',
            name='number_sediment_layers',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geologicalcontext',
            name='number_soil_horizons',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geologicalcontext',
            name='presence_coarse_components',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geologicalcontext',
            name='presence_vertical_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geologicalcontext',
            name='size_of_loess',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='geologicalcontext',
            name='surface_inclination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
