# Generated by Django 2.2.19 on 2021-04-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0006_auto_20210212_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='excavatedlithic',
            name='roet3',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='excavatedlithic',
            name='tipthick',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
    ]
