# Generated by Django 2.2.13 on 2020-10-14 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0007_auto_20200901_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='geologicalcontext',
            name='basis_of_record',
            field=models.CharField(blank=True, help_text='e.g. Observed item or Collected item', max_length=50, verbose_name='Basis of Record'),
        ),
        migrations.AddField(
            model_name='geologicalcontext',
            name='collecting_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Collecting Method'),
        ),
        migrations.AddField(
            model_name='geologicalcontext',
            name='date_collected',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Collected'),
        ),
        migrations.AddField(
            model_name='geologicalcontext',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='uploads/images/hrp'),
        ),
        migrations.AddField(
            model_name='geologicalcontext',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_context_recorded_by', to='psr.Person'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='date_collected',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Collected'),
        ),
    ]
