# Generated by Django 2.2.19 on 2021-04-30 17:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0008_auto_20210402_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excavationoccurrence',
            name='prism',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
