# Generated by Django 3.2.12 on 2022-05-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wormil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
