# Generated by Django 3.2.12 on 2022-05-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wormil', '0002_alter_specimen_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fossil',
            name='organism_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fossil',
            name='taxonomic_problem',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
