# Generated by Django 3.2.12 on 2022-05-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wormil', '0004_rename_finder_specimen_found_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='bed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
