# Generated by Django 3.2.12 on 2022-05-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wormil', '0005_alter_specimen_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='locality_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='verbatim_row_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
