# Generated by Django 3.2.12 on 2022-05-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wormil', '0006_auto_20220513_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name': 'Locality', 'verbose_name_plural': 'Locality'},
        ),
        migrations.AddField(
            model_name='locality',
            name='age_protocol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='archaeological_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='bed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='collection_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='dimension_ew',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='dimension_ns',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='earliest_age_ma',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='elevation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='georeference_protocol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='latest_age_ma',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='locality_boundary_east',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='locality_boundary_north',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='locality_boundary_south',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='locality_boundary_west',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='locality_decription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='macrobotanical_evidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='uncollected_taxa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='verbatim_age_ma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='year_established',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='formation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='member',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
