# Generated by Django 3.2.12 on 2022-05-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wormil', '0007_auto_20220514_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name': 'Locality', 'verbose_name_plural': 'Localities'},
        ),
        migrations.RenameField(
            model_name='locality',
            old_name='locality_decription',
            new_name='locality_description',
        ),
    ]
