# Generated by Django 3.2.12 on 2022-05-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wormil', '0008_auto_20220515_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='earliest_age_ma',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='latest_age_ma',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
