# Generated by Django 3.2.12 on 2022-05-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wormil', '0009_auto_20220515_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='archaeology_present',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='macrobotanical_present',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='uncollected_fossils_present',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
