# Generated by Django 3.2.12 on 2022-05-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wormil', '0011_auto_20220515_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fossil',
            options={'ordering': ['catalog_number']},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'ordering': ['locality_id'], 'verbose_name': 'Locality', 'verbose_name_plural': 'Localities'},
        ),
    ]
