# Generated by Django 3.2.12 on 2022-07-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('unit', models.CharField(blank=True, max_length=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('UM', 'Unordered Multistate'), ('OM', 'Ordered Multistate'), ('IN', 'Integer'), ('RN', 'Real Number'), ('TE', 'Text')], default='UM', max_length=5)),
                ('mandatory', models.BooleanField(blank=True, default=False, null=True)),
                ('multistate_type', models.IntegerField(default=1)),
                ('reliability', models.IntegerField(default=5)),
                ('availability', models.IntegerField(default=5)),
                ('fuzziness', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('fuzziness_is_percent', models.BooleanField(blank=True, default=False, null=True)),
                ('key_states', models.CharField(blank=True, max_length=5, null=True)),
                ('heading', models.IntegerField(blank=True, null=True)),
                ('heading_link', models.IntegerField(blank=True, null=True)),
                ('wording', models.TextField(blank=True, null=True)),
                ('alternate_wording', models.TextField(blank=True, null=True)),
                ('unit_is_prefix', models.BooleanField(blank=True, default=False, null=True)),
                ('format_string', models.TextField(blank=True, null=True)),
                ('paragraph_link', models.IntegerField(blank=True, null=True)),
                ('sentence_link', models.IntegerField(blank=True, null=True)),
                ('comma_link', models.IntegerField(blank=True, null=True)),
                ('special_link', models.IntegerField(blank=True, null=True)),
                ('special_element', models.IntegerField(blank=True, null=True)),
                ('use_comma', models.BooleanField(blank=True, default=False, null=True)),
                ('omit_final_comma', models.BooleanField(blank=True, default=False, null=True)),
                ('omit_values', models.BooleanField(blank=True, default=False, null=True)),
                ('emphasize', models.BooleanField(blank=True, default=False, null=True)),
                ('omit_period', models.BooleanField(blank=True, default=False, null=True)),
                ('num_states', models.IntegerField(blank=True, default=2, null=True)),
                ('char_ref', models.IntegerField(blank=True, null=True)),
                ('element', models.CharField(blank=True, choices=[('U', 'Upper Jaw'), ('L', 'Lower Jaw'), ('B', 'Both')], default='U', max_length=4, null=True)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('wording', models.CharField(blank=True, max_length=10, null=True)),
                ('format_string', models.CharField(blank=True, max_length=10, null=True)),
                ('implicit', models.BooleanField(blank=True, default=False, null=True)),
                ('use_edit', models.BooleanField(blank=True, default=True, null=True)),
                ('use_identify', models.BooleanField(blank=True, default=False, null=True)),
                ('use_description', models.BooleanField(blank=True, default=False, null=True)),
                ('use_phylo', models.BooleanField(blank=True, default=False, null=True)),
                ('use_other', models.BooleanField(blank=True, default=False, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idit.character')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('contact_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('contact_email', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wording', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('abundance', models.IntegerField(blank=True, null=True)),
                ('collection_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('lit_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('lit_key', models.IntegerField(blank=True, null=True)),
                ('lit_ref_detail', models.TextField(blank=True, null=True)),
                ('collection_code', models.CharField(blank=True, max_length=15, null=True)),
                ('specimen_no', models.CharField(blank=True, max_length=20, null=True)),
                ('taxonomic_order', models.CharField(blank=True, max_length=50, null=True)),
                ('disabled', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Item_Images')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus_name', models.CharField(max_length=50)),
                ('trivial_name', models.CharField(max_length=50)),
                ('common_name', models.CharField(max_length=50, null=True)),
                ('type_citation', models.TextField(null=True)),
                ('type_location_id', models.IntegerField(null=True)),
                ('type_specimen_no', models.CharField(max_length=100, null=True)),
                ('generic_type', models.BooleanField(blank=True, null=True)),
                ('genus_citation', models.TextField(null=True)),
                ('taxonomic_order', models.CharField(max_length=50, null=True)),
                ('taxonomic_family', models.CharField(max_length=50, null=True)),
                ('taxonomic_subfamily', models.CharField(max_length=50, null=True)),
                ('notes', models.TextField(null=True)),
                ('extant', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Item_Images')),
                ('description', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idit.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='idit.species'),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier', models.CharField(blank=True, max_length=10, null=True)),
                ('cs_value', models.CharField(blank=True, max_length=10, null=True)),
                ('x', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sequence', models.IntegerField(blank=True, default=0, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idit.character')),
                ('character_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='idit.characterstate')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idit.item')),
            ],
        ),
    ]
