# Generated by Django 3.2.12 on 2022-07-29 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='default_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Item_Images'),
        ),
        migrations.CreateModel(
            name='CharacterStateImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='CS_Images', verbose_name='Image')),
                ('description', models.TextField(blank=True, null=True)),
                ('default_image', models.BooleanField(default=False)),
                ('cs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idit.characterstate')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'managed': True,
            },
        ),
    ]
