from sermar.models import Locality, Collection, Occurrence
from rest_framework import serializers


class LocalitySerializer(serializers.ModelSerializer):
    """
    JSON serializer for Locality class in sermar.models.py.
    This class controls data exposed through the API endpoint at
    https://paleocore.org/sermar/api/localities
    """
    class Meta:
        model = Locality
        fields = ['name', 'roost_id', 'in_park', 'owls', 'owl_species', 'pellets', 'pellet_species',
                  'bones', 'sample_size', 'landmark', 'roost_type', 'analysis',
                  'accumulating_agent', 'protected_area', 'geom']


class CollectionSerializer(serializers.ModelSerializer):
    """
    JSON serializer for Collection class in sermar.models.py.
    This class controls data exposed through the API endpoint at
    https://paleocore.org/sermar/api/collections
    """

    # Two fields need special treatment because they are foreign key fields. The two approaches essentially produce
    # the same result -- a string representation of the related object -- but with different methods.
    # For the type_specimen field we retrieve the string representation of the type specimen object using the
    # StringRelatedField class of the serializer library.
    # For the taxon_rank field we specify calling the taxon_rank_label method of the Nomen class
    # which gets a string representation of the taxon rank, but one that is slightly different than the standard
    # string representation generated by the __str__ method of the TaxonRank class.
    locality = serializers.StringRelatedField()
    #taxon_rank = serializers.CharField(source='taxon_rank_label')

    class Meta:
        model = Collection
        fields = ['name', 'collection_code', 'roost_id', 'locality', 'date', 'specimen_loc',
                  'disposition', 'spec_start', 'spec_end', 'sample_size', 'source',
                  'status', 'comments', 'bags', 'weight', 'accumulating_agent']


class SpecimenSerializer(serializers.ModelSerializer):
    """
    JSON serializer for Specimen/Occurrence class in sermar.models.py
    This class controls data accessible through API endpoint at
    https://paleocore.org/sermar/api/specimens
    """
