# Generated by Django 3.2.5 on 2021-07-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lithic',
            name='multiple',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
