# Generated by Django 2.2.13 on 2021-02-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drp', '0003_auto_20200412_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='uploads/images/drp'),
        ),
    ]
