# Generated by Django 3.2.5 on 2021-07-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtap', '0004_auto_20200612_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='multiple',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
